// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuExSPH3uNydrjjlxXytzEjhT_l4xpQ6w',
    appId: '1:388083540119:web:2d485ab7e934a3cd9d89d2',
    messagingSenderId: '388083540119',
    projectId: 'airaapp-88e1f',
    authDomain: 'airaapp-88e1f.firebaseapp.com',
    storageBucket: 'airaapp-88e1f.firebasestorage.app',
    measurementId: 'G-G7V14SJ5ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHd4WwJpCE4iOHS_acBG6BCg2Gd6kmV0',
    appId: '1:388083540119:android:6fcfc61f8413a3629d89d2',
    messagingSenderId: '388083540119',
    projectId: 'airaapp-88e1f',
    storageBucket: 'airaapp-88e1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2cBGAxJAOKYHvQc7L-6fPQ8EnGedxUnw',
    appId: '1:388083540119:ios:c69d507bd98531699d89d2',
    messagingSenderId: '388083540119',
    projectId: 'airaapp-88e1f',
    storageBucket: 'airaapp-88e1f.firebasestorage.app',
    iosBundleId: 'com.example.airaapp',
  );
}
